kind: OverridePolicy
apiVersion: policy.kcloudlabs.io/v1alpha1
metadata:
  name: op-test
  namespace: default
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
      namespace: default
      name: web-1
  overrideRules:
    - targetOperations:
        - CREATE
        - UPDATE
      overriders:
        plaintext:
          - path: /metadata/annotations/hello
            op: add
            value: world
    - targetOperations:
        - CREATE
        - UPDATE
      overriders:
        cue: |-
          object: _ @tag(object)
          
          patches: [
            if object.metadata.annotations == _|_ {
              {
                op: "add"
                path: "/metadata/annotations"
                value: {}
              }
            },
            {
              op: "add"
              path: "/metadata/annotations/added-by"
              value: "cue"
            }
          ]
    - targetOperations:
        - CREATE
        - UPDATE
      overriders:
        template:
          type: annotations
          operation: add
          path: updated-by
          value:
            string: templatedPolicy